Device id: 43
Received 2 sensors: [{'sensor_id': 5, 'area_id': 6, 'type': 'SoilMoisture', 'name': 'Soil Moisture Sensor', 'unit': '%', 'threshold': {'max': 80, 'min': 20}, 'domain': {'max': 100, 'min': 0}, 'greenhouse_id': 13}, {'sensor_id': 1, 'area_id': 4, 'type': 'SoilMoisture', 'name': 'Soil Moisture Sensor', 'unit': '%', 'threshold': {'max': 80, 'min': 25}, 'domain': {'max': 100, 'min': 0}, 'greenhouse_id': 13}]
Subscribed to greenhouse_13/area_6/sensor_5
Subscribed to greenhouse_13/area_6/event/sensor_5
Subscribed to greenhouse_13/area_4/sensor_1
Subscribed to greenhouse_13/area_4/event/sensor_1
Connected to mqtt.eclipseprojects.io with result code 0

Received: {'bn': 'greenhouse_13/area_6/sensor_5', 'e': {'n': 'SoilMoisture', 'v': 49.716986065136254, 'u': '%', 't': 20}}
Error processing the message: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /get_next_timestamp?sensor_id=5&sensor_type=SoilMoisture&timestamp=20 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b10b67750a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Received: {'bn': 'greenhouse_13/area_4/sensor_1', 'e': {'n': 'SoilMoisture', 'v': 51.96656780551847, 'u': '%', 't': 20}}
Error processing the message: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /get_next_timestamp?sensor_id=1&sensor_type=SoilMoisture&timestamp=20 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b10b6775bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Received: {'bn': 'greenhouse_13/area_6/sensor_5', 'e': {'n': 'SoilMoisture', 'v': 50.92395979678155, 'u': '%', 't': 40}}
Error processing the message: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /get_next_timestamp?sensor_id=5&sensor_type=SoilMoisture&timestamp=40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b10b6776600>: Failed to establish a new connection: [Errno 111] Connection refused'))

Received: {'bn': 'greenhouse_13/area_4/sensor_1', 'e': {'n': 'SoilMoisture', 'v': 51.91047926055017, 'u': '%', 't': 40}}
Error processing the message: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /get_next_timestamp?sensor_id=1&sensor_type=SoilMoisture&timestamp=40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b10b6777050>: Failed to establish a new connection: [Errno 111] Connection refused'))

Received: {'bn': 'greenhouse_13/area_6/sensor_5', 'e': {'n': 'SoilMoisture', 'v': 48.188592306719194, 'u': '%', 't': 60}}
Error processing the message: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /get_next_timestamp?sensor_id=5&sensor_type=SoilMoisture&timestamp=60 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b10b6776cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Received: {'bn': 'greenhouse_13/area_4/sensor_1', 'e': {'n': 'SoilMoisture', 'v': 48.45331824831391, 'u': '%', 't': 60}}
Error processing the message: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /get_next_timestamp?sensor_id=1&sensor_type=SoilMoisture&timestamp=60 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b10b6776630>: Failed to establish a new connection: [Errno 111] Connection refused'))

Received: {'bn': 'greenhouse_13/area_6/sensor_5', 'e': {'n': 'SoilMoisture', 'v': 50.29592001124138, 'u': '%', 't': 80}}
Error processing the message: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /get_next_timestamp?sensor_id=5&sensor_type=SoilMoisture&timestamp=80 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b10b6775a30>: Failed to establish a new connection: [Errno 111] Connection refused'))

Received: {'bn': 'greenhouse_13/area_4/sensor_1', 'e': {'n': 'SoilMoisture', 'v': 50.93246181862321, 'u': '%', 't': 80}}
Error processing the message: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /get_next_timestamp?sensor_id=1&sensor_type=SoilMoisture&timestamp=80 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b10b6774ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Received: {'bn': 'greenhouse_13/area_6/sensor_5', 'e': {'n': 'SoilMoisture', 'v': 48.339568252733166, 'u': '%', 't': 100}}
WARNING: Failed to get when the next value of SoilMoisture (sensor_5) is expected to arrive
Telegram message sent successfully to user 2070801980

Received: {'bn': 'greenhouse_13/area_4/sensor_1', 'e': {'n': 'SoilMoisture', 'v': 49.241564329434574, 'u': '%', 't': 100}}
WARNING: Failed to get when the next value of SoilMoisture (sensor_1) is expected to arrive
Telegram message sent successfully to user 2070801980

Received: {'bn': 'greenhouse_13/area_6/sensor_5', 'e': {'n': 'SoilMoisture', 'v': 51.504652575185084, 'u': '%', 't': 120}}
The next value of SoilMoisture (sensor_5) is expected to be received at: 140.0
The next value of SoilMoisture (sensor_5) is expected to be: 54.669736897637 %
Wait to see another value to start the decision making for sensor_5 (SoilMoisture)

Received: {'bn': 'greenhouse_13/area_4/sensor_1', 'e': {'n': 'SoilMoisture', 'v': 48.34770084174563, 'u': '%', 't': 120}}
The next value of SoilMoisture (sensor_1) is expected to be received at: 140.0
The next value of SoilMoisture (sensor_1) is expected to be: 47.45383735405668 %
Wait to see another value to start the decision making for sensor_1 (SoilMoisture)

Received: {'bn': 'greenhouse_13/area_6/sensor_5', 'e': {'n': 'SoilMoisture', 'v': 51.681004388365636, 'u': '%', 't': 140}}
The next value of SoilMoisture (sensor_5) is expected to be received at: 160.0
The next value of SoilMoisture (sensor_5) is expected to be: 53.849844541060435 %
The measured value (51.681004388365636 %) and the next prediction (53.849844541060435 %) of sensor_5 (SoilMoisture) are inside the range [20, 80]
Telegram message sent successfully to user 2070801980

Received: {'bn': 'greenhouse_13/area_4/sensor_1', 'e': {'n': 'SoilMoisture', 'v': 48.83524000381647, 'u': '%', 't': 140}}
The next value of SoilMoisture (sensor_1) is expected to be received at: 160.0
The next value of SoilMoisture (sensor_1) is expected to be: 48.40184406604746 %
The measured value (48.83524000381647 %) and the next prediction (48.40184406604746 %) of sensor_1 (SoilMoisture) are inside the range [25, 80]
Telegram message sent successfully to user 2070801980

Received: {'bn': 'greenhouse_13/area_6/sensor_5', 'e': {'n': 'SoilMoisture', 'v': 48.21840225821017, 'u': '%', 't': 160}}
The next value of SoilMoisture (sensor_5) is expected to be received at: 180.0
The next value of SoilMoisture (sensor_5) is expected to be: 49.889120326026415 %
WARNING: The measured value 48.21840225821017 % of SoilMoisture (sensor_5) is unexpected. (Expected value was 49.889120326026415 %)	Waiting to receive another value
Telegram message sent successfully to user 2070801980

Received: {'bn': 'greenhouse_13/area_4/sensor_1', 'e': {'n': 'SoilMoisture', 'v': 48.57361129912351, 'u': '%', 't': 160}}
The next value of SoilMoisture (sensor_1) is expected to be received at: 180.0
The next value of SoilMoisture (sensor_1) is expected to be: 48.37044913631446 %
The measured value (48.57361129912351 %) and the next prediction (48.37044913631446 %) of sensor_1 (SoilMoisture) are inside the range [25, 80]
Telegram message sent successfully to user 2070801980
WARNING: Was expecting a value of SoilMoisture from sensor_5 at time 180.0, but it didn't arrive
Telegram message sent successfully to user 2070801980
WARNING: Was expecting a value of SoilMoisture from sensor_1 at time 180.0, but it didn't arrive
Telegram message sent successfully to user 2070801980
